apiVersion: v1
kind: Service
metadata:
  name: quakes-api
  labels:
    name: quakes-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3012
    targetPort: 3012
  selector:
    app: quakes-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quakes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quakes-api
  template:
    metadata:
      labels:
        app: quakes-api
    spec:
      containers:
        - image: chzbrgr71/quakes-api:v1.1
          imagePullPolicy: Always
          name: quakes-api
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: DATA_SERVICE_URI
              value: http://data-api.default.svc.cluster.local:3009/
          ports:
          - containerPort: 3012
            protocol: TCP
      restartPolicy: Always
