- name: Deploy AKS Infrastructure to support K8S Service Tracker Application
  hosts: localhost
  connection: local
  no_log: false
  vars_files:
    - ./vars-myvars.yml
  roles:
    - ../modules

  tasks:
    - name: Create a managed Azure Container Services (AKS) instance to support K8S Service Tracker Application
      azure_rm_aks:
        name: "{{ vm_name }}-aks"
        resource_group: "{{ resource_group }}"
        kubernetes_version: "1.15.12"
        dns_prefix: "{{ vm_name }}-dns"
        linux_profile:
          admin_username:  "{{ admin_username }}"
          ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        service_principal:
          client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
          client_secret: "{{ lookup('env', 'AZURE_SECRET') }}"
        agent_pool_profiles:
          - name: default
            count: 6 
            vm_size: Standard_D3_v2
        tags:
          Environment: RedHatSummit
      register: aks_output

    - debug:
        msg: "The name of your AKS cluster is: {{ aks_output.name }}. Please execute: 'az aks get-credentials -n {{ aks_output.name }} -g {{ resource_group }}'"
