---
#
# Deploy and scale Microsoft Azure Cloud Native infrastructures and applications with Red Hat Ansible Automation
#
#
resource_group: "MY_RESOURCE_GROUP"

# Asset Prefix
vm_name: "MYVM"

# Azure Data Center
location: "MYAZUREDATACENTER"

# Function App Exercise
github_id: "MYGITHUBID"
github_token: "MYGITHUBPERSONALACCESSTOKEN"

# The admin username that you would like to use for all of your VM assets. You will likely not need to connect to them.
admin_username: student

# Random Generated Number
rnum: "MYRANDOM"

# Complex Password
admin_password: "MuABCPassword!!@123"

# Create Azure Managed MySQL Database (PaaS) Exercise
mysql_username: "mmuser"
mysql_password: "Testpasswordxyz12!"
mysql_database_name: "mattermost"

# HPC Lab Exercise
hp_infra_size: "Standard_D4s_v3"
hp_compute_size: "Standard_A8"

# ARO Lab Exercise
aro_username: "MYUSERNAME"
